"""empty message

Revision ID: df177200df9e
Revises: f9d27652a7cb
Create Date: 2022-12-09 00:15:11.402315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df177200df9e"
down_revision = "f9d27652a7cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=120),
            type_=sa.String(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=120),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
